### ISSUE TITLE
Incorrect Solution for Exercise 6.4.4

### ISSUE THREAD

**Issue by brooklynbagel** [bnaras/cvxr_tutorial#1]
## Issue

Given the problem stated "Fit OLS with just the following order constraints on β: β_i≤β_{i+1} for i=1,…,4 and β_i≥β_{i+1} for i=5,…,p.", the solution should have beta_1 <= beta_2 ... beta4_ <= beta_5 and beta_5 >= beta_6 ... beta_9 >= beta_10. 

However, the solution given doesn't satisfy this requirement.

```r
D1 <- D2 <- diag(0, p)
D1[1:5, 1:5] <- 1; D2[5:p, 5:p] <- 1;
D3 <- D4 <- diag(0, p - 1)
D3[1:4, 1:4] <- 1; D4[5:(p-1), 5:(p-1)] <- 1;
constraints = list(D3 %*% diff(D1 %*% beta) >= 0, D4 %*% diff(D2 %*% beta) <= 0)
problem4 <- Problem(objective, constraints)
ex4 <- solve(problem4)
betaEstimate <- ex4$getValue(beta)
```

results in

|        |           |
|:-------|----------:|
|beta_1  | -3.9025328|
|beta_2  | -2.9683386|
|beta_3  | -1.8234267|
|beta_4  | -1.1562133|
|beta_5  |  0.0753986|
|beta_6  |  0.9224317|
|beta_7  |  1.8799511|
|beta_8  |  3.1107020|
|beta_9  |  4.1086503|
|beta_10 |  5.0947592|

## Potential Solution

I believe something akin to the below would satisfy the constraints of the problem as stated.

```r
# generate (p-1) x p matrix for both constraints
# beta_1 <= beta_2 implies beta_2 - beta_1 >= 0, etc.
# and beta_5 >= beta_6 implies beta_5 - beta_6 >= 0, etc.
ones <- diag(1, p)
d1 <- ones[-1, ] - ones[-10,]
d1[-(1:4),] <- 0
d2 <- ones[-10,] - ones[-1,]
d2[1:4,] <- 0
d <- d1 + d2

constraints <- list(d %*% beta >= 0)
problem <- Problem(objective, constraints)
result <- solve(problem1)
result$getValue(beta)
```

has a result of

|        |          |
|:-------|---------:|
|beta_1  | -4.124667|
|beta_2  | -2.731246|
|beta_3  | -1.739471|
|beta_4  | -1.456388|
|beta_5  |  2.823590|
|beta_6  |  2.823590|
|beta_7  |  2.823590|
|beta_8  |  2.823590|
|beta_9  |  2.823590|
|beta_10 |  2.823590|

**Comment by bnaras** [comment]
Thanks for the report. Yes, was solving the wrong problem as written. Corrected as follows:

```
D1 <- cbind(diag(5), diag(0, 5))
D2 <- cbind(matrix(0, 6, 4), diag(6))
constraints = list(diff(D1 %*% beta) >= 0, diff(D2 %*% beta) <= 0)
problem4 <- Problem(objective, constraints)
...
```
